[project]
name = "default"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "konsave>=2.2.0",
    "qmk>=1.1.8",
    "rofi-rbw>=1.5.1",
    "rofimoji>=6.7.0",
    "setuptools>=80.9.0",
]
